package net.aura.proto

const val MSG_FLAGS_LENGTH = 1

const val MSG_FLAGS_TYPE_MASK : Byte = 0b00000011
const val MSG_FLAGS_BROADCAST_PRIVATE_MASK: Byte = 0b00000100
const val MSG_FLAGS_GLOBAL_REGISTRY_MASK: Byte = 0b00001000

const val MSG_FLAGS_TYPE_DIRECT: Byte = 0b00
const val MSG_FLAGS_TYPE_BROADCAST: Byte = 0b01

const val MSG_DIRECT_SENDERPUB_LENGTH = 32
const val MSG_DIRECT_FILTER_LENGTH = 1
const val MSG_DIRECT_INTEGRITY_LENGTH = 4

const val MSG_BROADCAST_SENDERPUB_LENGTH = 32
const val MSG_BROADCAST_SIGN_LENGTH = 64

const val MSG_NONCE_LENGTH = 4
const val MSG_TIME_LENGTH = 5


const val MSG_MIN_LENGTH = MSG_FLAGS_LENGTH + MSG_TIME_LENGTH + MSG_NONCE_LENGTH
const val MSG_DIRECT_MIN_LENGTH = MSG_MIN_LENGTH + MSG_DIRECT_SENDERPUB_LENGTH + MSG_DIRECT_FILTER_LENGTH + MSG_DIRECT_INTEGRITY_LENGTH
const val MSG_BROADCAST_MIN_LENGTH = MSG_MIN_LENGTH + MSG_BROADCAST_SENDERPUB_LENGTH + MSG_BROADCAST_SIGN_LENGTH


//MESSAGE
//|flags|time|details|nonce|

//DIRECT MESSAGE DETAILS
//|senderpub|filter|content|integrity|

//BROADCAST MESSAGE
//|senderpub|content|sign|

//OFFSETS
const val MSG_FLAGS_OFFSET = 0
const val MSG_TIME_OFFSET = MSG_FLAGS_OFFSET+MSG_FLAGS_LENGTH
const val MSG_DETAILS_OFFSET = MSG_TIME_OFFSET+MSG_TIME_LENGTH
const val MSG_NONCE_COUNTEROFFSET = -MSG_NONCE_LENGTH

const val MSG_DIRECT_SENDERPUB_OFFSET = MSG_DETAILS_OFFSET
const val MSG_DIRECT_FILTER_OFFSET = MSG_DIRECT_SENDERPUB_OFFSET + MSG_DIRECT_SENDERPUB_LENGTH
const val MSG_DIRECT_CONTENT_OFFSET = MSG_DIRECT_FILTER_OFFSET + MSG_DIRECT_FILTER_LENGTH
const val MSG_DIRECT_INTEGRITY_COUNTEROFFSET = MSG_NONCE_COUNTEROFFSET - MSG_DIRECT_INTEGRITY_LENGTH

const val MSG_BROADCAST_SENDERPUB_OFFSET = MSG_DETAILS_OFFSET
const val MSG_BROADCAST_CONTENT_OFFSET = MSG_BROADCAST_SENDERPUB_OFFSET + MSG_BROADCAST_SENDERPUB_LENGTH
const val MSG_BROADCAST_SIGN_COUNTEROFFSET = MSG_NONCE_COUNTEROFFSET - MSG_BROADCAST_SIGN_LENGTH

